name: build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  b3270:
    strategy:
      matrix:
        package: [b3270, b3270-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build .#${{ matrix.package }} -L
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}
          path: result/bin/
